language: node_js
node_js:
  - "7"
script:
  - sh -c 'cd karteikarten_app_mwb && npm run build'
install:
  - sh -c 'cd karteikarten_app_mwb && npm install -g firebase-tools'
  - sh -c 'cd karteikarten_app_mwb && npm install'
  - sh -c 'cd karteikarten_app_mwb/functions && npm install'
after_success:
  - sh -c 'cd karteikarten_app_mwb && firebase deploy --token $FIREBASE_TOKEN'
